-- V1__Initial_Schema_Oracle.sql
-- Migração inicial do banco de dados para a plataforma de Upskilling/Reskilling (Oracle)
-- Todas as tabelas, constraints e índices usam o prefixo "TRILHAS_"

-- =====================================================================
-- Cleanup procedure - DROP + CREATE FRESH
-- Ao executar este script, o bloco abaixo tentará DROPAR as
-- tabelas já existentes com prefixo TRILHAS_ (em ordem segura),
-- permitindo uma reaplicação limpa. Isso é ideal para dev/test.
-- Em produção, remova este bloco se não desejar apagar dados.
-- =====================================================================

DECLARE
  v_table VARCHAR2(200);
  TYPE t_names IS TABLE OF VARCHAR2(200);
  v_tables t_names := t_names(
    'TRILHAS_TRILHA_COMPETENCIA',
    'TRILHAS_MATRICULAS',
    'TRILHAS_COMPETENCIAS',
    'TRILHAS_TRILHAS',
    'TRILHAS_USUARIOS'
  );
BEGIN
  FOR i IN v_tables.FIRST .. v_tables.LAST LOOP
    v_table := v_tables(i);
    BEGIN
      -- Tenta dropar tabela com CASCADE CONSTRAINTS (se existir)
      EXECUTE IMMEDIATE 'DROP TABLE ' || v_table || ' CASCADE CONSTRAINTS';
      DBMS_OUTPUT.PUT_LINE('Tabela ' || v_table || ' removida com sucesso.');
    EXCEPTION
      WHEN OTHERS THEN
        -- Se a tabela não existir, ignora e continua
        IF SQLCODE = -942 THEN
          -- ORA-00942: table or view does not exist
          DBMS_OUTPUT.PUT_LINE('Tabela ' || v_table || ' não existe (esperado na primeira execução).');
        ELSE
          -- Outro erro: ignora silenciosamente
          NULL;
        END IF;
    END;
  END LOOP;
  DBMS_OUTPUT.PUT_LINE('Cleanup concluído. Pronto para criar novo schema.');
END;
/

-- =====================================================================
-- Observações:
-- 1) Usa colunas IDENTITY (Oracle 12c+). Se precisar de compatibilidade com versões antigas,
--    eu posso gerar uma versão com SEQUENCE + TRIGGER por tabela.
-- 2) TEXT foi convertido para CLOB; VARCHAR/INT ajustados para VARCHAR2/NUMBER.
-- =====================================================================

-- Tabela de usuários da plataforma
CREATE TABLE TRILHAS_USUARIOS (
    id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nome VARCHAR2(100) NOT NULL,
    email VARCHAR2(150) NOT NULL,
    area_atuacao VARCHAR2(100),
    nivel_carreira VARCHAR2(50),
    data_cadastro DATE NOT NULL,
    CONSTRAINT TRILHAS_USUARIOS_PK PRIMARY KEY (id),
    CONSTRAINT TRILHAS_USUARIOS_UQ_EMAIL UNIQUE (email)
);

-- Tabela de trilhas de aprendizagem
CREATE TABLE TRILHAS_TRILHAS (
    id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nome VARCHAR2(150) NOT NULL,
    descricao CLOB,
    nivel VARCHAR2(50) NOT NULL,
    carga_horaria NUMBER(10) NOT NULL,
    foco_principal VARCHAR2(100),
    CONSTRAINT TRILHAS_TRILHAS_PK PRIMARY KEY (id)
);

-- Tabela de competências (skills)
CREATE TABLE TRILHAS_COMPETENCIAS (
    id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nome VARCHAR2(100) NOT NULL,
    categoria VARCHAR2(100),
    descricao CLOB,
    CONSTRAINT TRILHAS_COMPETENCIAS_PK PRIMARY KEY (id)
);

-- Relação N:N entre trilhas e competências
CREATE TABLE TRILHAS_TRILHA_COMPETENCIA (
    trilha_id NUMBER(19) NOT NULL,
    competencia_id NUMBER(19) NOT NULL,
    CONSTRAINT TRILHAS_TRILHA_COMPETENCIA_PK PRIMARY KEY (trilha_id, competencia_id),
    CONSTRAINT TRILHAS_TRILHA_COMPETENCIA_FK_TRILHA FOREIGN KEY (trilha_id)
        REFERENCES TRILHAS_TRILHAS (id) ON DELETE CASCADE,
    CONSTRAINT TRILHAS_TRILHA_COMPETENCIA_FK_COMP FOREIGN KEY (competencia_id)
        REFERENCES TRILHAS_COMPETENCIAS (id) ON DELETE CASCADE
);

-- Matrícula de usuários em trilhas
CREATE TABLE TRILHAS_MATRICULAS (
    id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    usuario_id NUMBER(19) NOT NULL,
    trilha_id NUMBER(19) NOT NULL,
    data_inscricao DATE NOT NULL,
    status VARCHAR2(50) NOT NULL,
    data_conclusao DATE,
    progresso_percentual NUMBER(3),
    data_cancelamento DATE,
    avaliacao NUMBER(1),
    CONSTRAINT TRILHAS_MATRICULAS_PK PRIMARY KEY (id),
    CONSTRAINT TRILHAS_MATRICULAS_FK_USUARIO FOREIGN KEY (usuario_id)
        REFERENCES TRILHAS_USUARIOS (id) ON DELETE CASCADE,
    CONSTRAINT TRILHAS_MATRICULAS_FK_TRILHA FOREIGN KEY (trilha_id)
        REFERENCES TRILHAS_TRILHAS (id) ON DELETE CASCADE,
    CONSTRAINT TRILHAS_MATRICULAS_CHK_PROGRESSO CHECK (progresso_percentual BETWEEN 0 AND 100),
    CONSTRAINT TRILHAS_MATRICULAS_CHK_AVALIACAO CHECK (avaliacao BETWEEN 1 AND 5)
);

-- Índices para otimização (não redundantes com constraints existentes)
-- Nota: Oracle cria automaticamente índices para PRIMARY KEY e UNIQUE constraints
-- Portanto, apenas criamos índices para colunas de foreign key e filtros comuns
CREATE INDEX TRILHAS_TRILHAS_IDX_NIVEL ON TRILHAS_TRILHAS(nivel);
CREATE INDEX TRILHAS_MATRICULAS_IDX_USUARIO ON TRILHAS_MATRICULAS(usuario_id);
CREATE INDEX TRILHAS_MATRICULAS_IDX_TRILHA ON TRILHAS_MATRICULAS(trilha_id);
CREATE INDEX TRILHAS_MATRICULAS_IDX_STATUS ON TRILHAS_MATRICULAS(status);
